baseURL = 'https://elephantstarballoon.com/'
languageCode = 'en-us'
title = 'ğŸ˜â­ğŸˆ'
theme = 'PaperMod'

[params]
disableThemeToggle = true

[[menu.main]]
name = 'Github'
url = 'https://github.com/Nycto'
weight = 10

[[menu.main]]
name = 'Mastadon'
url = 'https://mstdn.games/@Nycto'
weight = 20

[[menu.main]]
name = 'BlueSky'
url = 'https://bsky.app/profile/jarmsicle.bsky.social'
weight = 30

[[menu.main]]
name = 'Itch'
url = 'https://elephantstarballoon.itch.io/'
weight = 40
